[package]
name = "trie"
version = "0.1.0"
authors = ["Frank McSherry <fmcsherry@me.com>"]

[dependencies]
rand="*"
fnv="1.0.2"

[dependencies.graph_map]
git="http://github.com/frankmcsherry/graph-map"

[profile.release]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false